### ISSUE TITLE
[bug][tbcc] Addon action forbidden - Opening Guild Pane

### ISSUE THREAD

**Issue by Laumesis** [leatrix/leatrix-maps-bcc#39] opened 2021-09-03 02:13 UTC
WoW v2.5.2.40011
All other addons disabled. Only Leatrix_Maps BCC v2.5.54 enabled.
Game restarted.
1. Login character (that is in guild). Or reload ui.
2. Press keybinding for `Toggle World Map Pane` twice. (i.e. open and close world map)
3. Press keybinding for `Toggle Guild Pane` once.
4. Leatrix_Maps shows its own popup for ADDON_ACTION_FORBIDDEN.

**Comment by Laumesis** [comment] 2021-09-03 02:16
Settings:
```lua
LeaMapsDB = {
	["MapScale"] = 0.805493056774139,
	["AutoChangeZones"] = "Off",
	["ShowZoneLevels"] = "On",
	["RescaleMap"] = "Off",
	["LockMapFrame"] = "On",
	["MapPosA"] = "TOPLEFT",
	["stationaryOpacity"] = 1,
	["tintRed"] = 0.3,
	["BattleMapX"] = -47,
	["MainPanelA"] = "CENTER",
	["ShowTravelPoints"] = "Off",
	["BattleMapOpacity"] = 1,
	["ShowCoords"] = "Off",
	["ShowMinimapIcon"] = "Off",
	["BattleMapSize"] = 1,
	["EnhanceBattleMap"] = "Off",
	["tintAlpha"] = 1,
	["ShowSpiritHealers"] = "Off",
	["SetMapOpacity"] = "On",
	["StickyMapFrame"] = "Off",
	["BattleMapR"] = "BOTTOMRIGHT",
	["MapPosR"] = "TOPLEFT",
	["BattlePlayerArrowSize"] = 12,
	["MapPosX"] = 55.3241310119629,
	["FadeMap"] = "On",
	["UseClassIcons"] = "On",
	["RememberZoom"] = "Off",
	["MainPanelX"] = 0,
	["MainPanelR"] = "CENTER",
	["UnlockMapFrame"] = "On",
	["BattleMapA"] = "BOTTOMRIGHT",
	["ShowScaleHandle"] = "Off",
	["PlayerArrowSize"] = 27,
	["RevealMap"] = "On",
	["ClassIconSize"] = 20,
	["UseDefaultMap"] = "Off",
	["ShowPointsOfInterest"] = "On",
	["minimapPos"] = 204,
	["MapPosY"] = -101.492492675781,
	["ShowFishingLevels"] = "On",
	["ShowFlightPoints"] = "Off",
	["hide"] = true,
	["movingOpacity"] = 0.3,
	["MainPanelY"] = 0,
	["NoMapBorder"] = "Off",
	["EnlargePlayerArrow"] = "Off",
	["BattleMapY"] = 83,
	["tintBlue"] = 0.3,
	["ShowDungeonIcons"] = "On",
	["NoFadeCursor"] = "On",
	["FadeLevel"] = 0.6,
	["FirstRunMessageSeen"] = true,
	["RevTint"] = "On",
	["BattleGroupIconSize"] = 20,
	["HideTownCityIcons"] = "On",
	["tintGreen"] = 0.3,
	["UnlockBattlefield"] = "On",
}
```

**Comment by leatrix** [comment] 2021-09-03 04:20
Thanks for the report and for including your chosen settings.

This seems to be dropdown menu taint.  The following options can cause the error to show:

- Enlarge player arrow: Regardless of the setting, this sets WorldMapUnitPinSizes.player to a value.
- Show points of interest: Regardless of the setting, this adds the points of interest data provider.
- Use default map: If this option is disabled, WorldMapFrame.ScrollContainer.GetCursorPosition() is replaced so that it takes different map scales into account.

Disabling the first two settings won't fix it as the code for those options is run regardless of whether they are enabled or not (no reloads required).  Enabling the third setting fixes it for the map scale issue but you would still see taint from the first two settings.

And to reproduce it:

- Reload UI.
- Open and close the world map.
- Open the guild panel.
- Sometimes it's necessary to toggle the 'Show offline members' checkbox too.

Enabling 'Remove map border' seems to fix it as it hides the dropdown menus on the world map frame.  So as a workaround in 2.5.51.alpha.1, the zone and continent dropdown menus are hidden regardless of whether the map border is enabled or not.  Please try it and let me know how you go on with it.

https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

**Comment by Laumesis** [comment] 2021-09-08 00:14
Doesn't help fully as **any** dropdownmenu utilising blizzard dropdownmenu may cause it if operated before opening FriendFrame first time. I hope they fix the bug soon. https://github.com/Stanzilla/WoWUIBugs/issues/165

There exists a workaround to initialize guild stuff at login, but it is not good one if every addon starts to implement it.

**Comment by leatrix** [comment] 2021-09-08 00:30
Yes, I expect you're right.  Are you able to reproduce the guild frame taint since the dropdown menus were removed?

**Comment by Tenies** [comment] 2021-09-15 13:19
I was about to report that the "Continent" and "Zone" menus on world map are hidden but i see now.
It would be nice to have the options to hide them as also the "Zone Map" menu and "Zoom out" button. I like to keep my map clean!

**Comment by leatrix** [comment] 2021-09-15 13:35
Did you try removing the map border entirely?  Not what you want?

**Comment by Tenies** [comment] 2021-09-25 05:19
> Did you try removing the map border entirely? Not what you want?

Not really cause coords and few addon icons are on the air.

**Comment by leatrix** [comment] 2021-09-25 07:36
Try 2.5.58.alpha.1.  It moves the zone map dropdown menu to the main panel and hides the zoom out button.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files

**Closed** 2021-10-09 20:49 UTC
Labels: help
